In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import seaborn as sns

In [ ]:
df = pd.read_csv('/archive (5).zip')
df

FileNotFoundError: ignored

In [ ]:
df.tail()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [ ]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,486.000000,486.000000,486.000000,486.000000,506.000000,506.000000,486.000000,506.000000,506.000000,506.000000,506.000000,506.000000,486.000000,506.000000
mean,3.611874,11.211934,11.083992,0.069959,0.554695,6.284634,68.518519,3.795043,9.549407,408.237154,18.455534,356.674032,12.715432,22.532806
std,8.720192,23.388876,6.835896,0.255340,0.115878,0.702617,27.999513,2.105710,8.707259,168.537116,2.164946,91.294864,7.155871,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.081900,0.000000,5.190000,0.000000,0.449000,5.885500,45.175000,2.100175,4.000000,279.000000,17.400000,375.377500,7.125000,17.025000
50%,0.253715,0.000000,9.690000,0.000000,0.538000,6.208500,76.800000,3.207450,5.000000,330.000000,19.050000,391.440000,11.430000,21.200000
75%,3.560263,12.500000,18.100000,0.000000,0.624000,6.623500,93.975000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [ ]:
df.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [ ]:
df.iloc[0:2,1:2]

NameError: ignored

In [ ]:
df1 = df.drop(columns= ['CRIM','ZN', 'INDUS', 'CHAS', 'AGE', 'LSTAT'])
df1

       NOX     RM     DIS  RAD  TAX  PTRATIO       B  MEDV
0    0.538  6.575  4.0900    1  296     15.3  396.90  24.0
1    0.469  6.421  4.9671    2  242     17.8  396.90  21.6
2    0.469  7.185  4.9671    2  242     17.8  392.83  34.7
3    0.458  6.998  6.0622    3  222     18.7  394.63  33.4
4    0.458  7.147  6.0622    3  222     18.7  396.90  36.2
..     ...    ...     ...  ...  ...      ...     ...   ...
501  0.573  6.593  2.4786    1  273     21.0  391.99  22.4
502  0.573  6.120  2.2875    1  273     21.0  396.90  20.6
503  0.573  6.976  2.1675    1  273     21.0  396.90  23.9
504  0.573  6.794  2.3889    1  273     21.0  393.45  22.0
505  0.573  6.030  2.5050    1  273     21.0  396.90  11.9

[506 rows x 8 columns]

In [ ]:
df1.isnull().sum()

NOX        0
RM         0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
MEDV       0
dtype: int64

In [ ]:
x = df1.iloc[:, 0:13]
y = df1.iloc[:,-1]

In [ ]:
x = df1.iloc[0:1,0:1]
y = df1.iloc[:,0:3]
x

     NOX
0  0.538

In [ ]:
x = df1.iloc[0]

NameError: ignored

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.20,random_state=42)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(x_train.shape)
print(x_test.shape)

(404, 8)
(102, 8)
(404, 8)
(102, 8)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [ ]:
model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())
model.fit(x_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler(with_mean=False)),
                ('linearregression', LinearRegression())])

In [ ]:
model.score(x_test, y_test)

1.0